# Generated by Django 4.0.4 on 2022-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todowoo',
            name='datecompleted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
