# Generated by Django 4.0.4 on 2022-07-09 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todowoo_datecompleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todowoo',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='todowoo',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
